---
# Playbook to Backup all config and produce show outputs

- hosts: localhost
  gather_facts: false
  
  tasks:
   - name: Get ansible date/time facts
     setup:
       filter: "ansible_date_time"
       gather_subset: "!all"

   - name: Store DTG as fact
     set_fact:
       DTG: "{{ ansible_date_time.date }}"

   - name: Create Directory {{hostvars.localhost.DTG}} 
     file: 
      path: ~/apefne/backups/{{hostvars.localhost.DTG}}
      state: directory
