---
- hosts: "{{ log_server }}"
  tasks:
  - name: Make log directory
    file:
      state: directory
      path: /var/log/remote_logs

  - name: Grab log file
    copy:
     src: "{{ log_file }}"
     dest: /var/log/remote_logs/{{ source_server }}-{{ log_file | basename }}
     remote_src: yes
    delegate_to: "{{ source_server }}"
