---
- hosts: all
  tasks:
  - name: Make log directory on log server
    file:
      state: directory
      path: /var/log/remote_logs
    delegate_to: "{{ log_server }}"

  - name: Grab log file
    fetch:
      src: "{{ log_file }}"
      dest: /tmp/{{ inventory_hostname }}-{{ log_file | basename }}
      flat: yes
      validate_checksum: no

  - name: Copy log file to log server
    copy:
     src: /tmp/{{ inventory_hostname }}-{{ log_file | basename }}
     dest: /var/log/remote_logs/{{ inventory_hostname }}-{{ log_file | basename }}
    delegate_to: "{{ log_server }}"

  - name: Clean up log file locally
    file:
      path: /tmp/{{ inventory_hostname }}-{{ log_file | basename }}
      state: absent
