---

- name: Install httpd
  yum:
    name: httpd
    state: installed

- name: Start and enable httpd
  service:
    name: httpd
    state: started
    enabled: yes

- name: Configure Web Content
  template: 
    dest: /var/www/html/index.html 
    src: index.html.j2
  notify:
    - restart httpd
