---

- name: Install Red Hat Access Insights Client
  yum: name={{ item }} state=present
  with_items:
      - redhat-access-insights

- name: Configure Red Hat Access Insights Client
  template: src=insights-client.conf.j2 dest=/etc/redhat-access-insights/redhat-access-insights.conf

- name: Check status of Insights .unregister file
  stat: path=/etc/insights-client/.unregistered
  register: unreg_file_task

- name: Check status of Insights .register file
  stat: path=/etc/insights-client/.registered
  register: reg_file_task

- name: Unregister if we are setting the display_name, and we have already registered
  command: redhat-access-insights --unregister
  when:
    - insights_display_name is defined
    - unreg_file_task.stat.exists == false
    - reg_file_task.stat.exists == true
  register: unreg_task

# Only register if this system hasn't been registered before
- name: Register to the Red Hat Access Insights Service
  command: redhat-access-insights --register {{ '--display-name='+insights_display_name if insights_display_name is defined else '' }} creates=/etc/insights-client/.registered
  when: unreg_file_task.stat.exists == false
  register: reg_task

- name: Downgrade sudo to test Insights
  yum:
    name: sudo-1.8.6p7-21.el7_3.x86_64
    state: present
    allow_downgrade: true
