---

- name: Check for available updates
  shell: yum check-update
  args:
    warn: false
  register: yum_updates
  failed_when: yum_updates.rc == 1

- name: Remove server from loadbalancer pool
  haproxy:
    state: disabled
    socket: /var/lib/haproxy/stats
    host: "{{ inventory_hostname }}"
    backend: http
  delegate_to: "{{ groups.loadbalancers | first }}"
  when: yum_updates.rc == 100

- name: Auth to RHV so we can take a snapshot
  ovirt_auth:
    url: "{{ auth_url }}"
    username: "{{ username }}"
    password: "{{ password }}"
    insecure: true
  delegate_to: "{{ rhv_man }}"
  when: yum_updates.rc == 100 and hostvars[inventory_hostname][ansible_facts][ansible_virtualization_type] != 'kvm'

- name: Take snapshot of RHV VM
  ovirt_snapshots:
    auth: "{{ ovirt_auth }}"
    vm_name: "{{ inventory_hostname }}"
    description: "{{ snapshot_description }}"
    use_memory: false 
  delegate_to: "{{ rhv_man }}"
  when: yum_updates.rc == 100

- name: Take snapshot of libvirt VM
  shell: virsh snapshot-create-as "{{ inventory_hostname }}" --name "{{ snapshot_description }}" 
  when: yum_updates.rc == 100 and hostvars[inventory_hostname][ansible_facts][ansible_virtualization_type] == 'kvm'

- name: Patch Server
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - kernel
    - dhclient
  when: yum_updates.rc == 100
  register: patched

- name: Reboot server
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true
  when: patched is changed

- name: Wait for server to come back
  wait_for: 
    host: "{{ inventory_hostname }}"
    delay: 10 
    timeout: 300 
    port: 22
  delegate_to: localhost
  when: patched is changed

- name: Add server back into loadbalancer pool
  haproxy:
    state: enabled
    socket: /var/lib/haproxy/stats
    host: "{{ inventory_hostname }}"
    backend: http
  delegate_to: "{{ groups.loadbalancers | first }}"
  when: patched is changed

- name: run insights
  command: redhat-access-insights
  when: patched is changed

- name: Pause for 15 seconds
  pause:
    seconds: 15
